=== appliedengdesign/cnccodes-json-schema/src/schemas/draft/2022-07/cnccodes.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://appliedengdesign.github.io/cnccodes-json-schema/draft/2022-07/schema",
    "title": "G/M Code Dictionary",
    "description": "JSON Schema for CNC G & M Codes",
    "type": "object",
    "required": ["title", "description", "type", "machineType"],
    "properties": {
        "$schema": {
            "description": "Link to this schema",
            "type": "string"
        },
        "title": {
            "description": "Descriptive title of the JSON Reference",
            "type": "string"
        },
        "description": {
            "description": "Description of the JSON Reference",
            "type": "string"
        },
        "keywords": {
            "description": "An Array of string keywords describing the JSON Reference (Optional)",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "type": {
            "description": "The type of code (G or M)",
            "type": "string",
            "enum": ["gcode", "mcode"]
        },
        "machineType": {
            "description": "The type of CNC machine",
            "type": "string",
            "enum": ["edm", "mill", "lathe", "laser", "printer", "swiss"]
        },
        "variant": {
            "description": "Defined if G/M Codes are for specific MTB/3DP Variant. (Must be lower case, 3-8 characters)",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 8,
                    "pattern": "[a-z0-9]"
                },
                "remove": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "uniqueItems": true
                }
            }
        },
        "codes": {
            "description": "Individual G/M Codes",
            "type": "object",
            "patternProperties": {
                "^G|^M": {
                    "type": "object",
                    "properties": {
                        "category": {
                            "description": "Category for the code",
                            "type": "string",
                            "enum": ["motion", "coordinate", "compensation", "canned", "other", "mcode"]
                        },
                        "modal": {
                            "description": "Modal / Non-Modal (boolean)",
                            "type": "boolean"
                        },
                        "shortDesc": {
                            "description": "A short description of the code",
                            "type": "string",
                            "minLength": 3
                        },
                        "desc": {
                            "description": "A longer description with markdown formatting",
                            "type": "string",
                            "minLength": 3
                        },
                        "parameters": {
                            "$ref": "#/$defs/parameters"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["category", "shortDesc"]
                },
                "additionalProperties": false
            },
            "minProperties": 1
        }
    },
    "additionalProperties": false,
    "$defs": {
        "parameters": {
            "description": "An array of possible parameters to the code",
            "type": "object",
            "patternProperties": {
                "^[A-Z]{1}": {
                    "type": "object",
                    "properties": {
                        "shortDesc": {
                            "description": "A short description of the parameter",
                            "type": "string",
                            "minLength": 3
                        },
                        "desc": {
                            "description": "A description of the parameter",
                            "type": "string",
                            "minLength": 3
                        },
                        "optional": {
                            "description": "Parameter is required (boolean)",
                            "type": "boolean"
                        }
                    },
                    "required": ["shortDesc", "optional"],
                    "additionalProperties": false
                }
            },
            "minProperties": 1
        }
    }
}

=== appliedengdesign/cnccodes-json-schema/test/sample/g-sample.json
{
    "$schema": "../../src/schema/cnccodes.schema.json",
    "type": "gcode",
    "machineType": "mill",
    "title": "G Code Milling Reference",
    "description": "G-Code Reference for Milling Machine Tools",
    "codes": {
        "G00": {
            "category": "motion",
            "shortDesc": "Rapid Motion Positioning",
            "desc": "G00 is used to move the machine axes at the maximum speed. This G code is modal.",
            "modal": true,
            "parameters": {
                "X": {
                    "shortDesc": "X-Axis motion command",
                    "optional": true
                },
                "Y": {
                    "shortDesc": "Y-Axis motion command",
                    "optional": true
                },
                "Z": {
                    "desc": "Z-Axis motion command",
                    "optional": true
                }
            }
        }
    }
}

=== appliedengdesign/cnccodes-json-schema/samples/latest/variant.valid.json
{
    "$schema": "../../src/schemas/draft/2022-07/cnccodes.schema.json",
    "type": "gcode",
    "machineType": "mill",
    "title": "G Code Milling Reference",
    "description": "M Code Reference for Milling Machine Tools",
    "keywords": ["mazak", "mill", "milling"],
    "variant": {
        "name": "snpmaker",
        "remove": ["M07", "M08"]
    },
    "codes": {
        "G00": {
            "category": "motion",
            "shortDesc": "Rapid Motion Positioning",
            "desc": "G00 is used to move the machine axes at the maximum speed. This G code is modal.",
            "modal": true,
            "parameters": {
                "X": {
                    "shortDesc": "X-Axis motion command",
                    "optional": true
                },
                "Y": {
                    "shortDesc": "Y-Axis motion command",
                    "optional": true
                },
                "Z": {
                    "shortDesc": "Z-Axis motion command",
                    "optional": true
                }
            }
        }
    }
}

=== appliedengdesign/cnccodes-json-schema/samples/latest/m.valid.json
{
    "$schema": "../../src/schemas/draft/2022-07/cnccodes.schema.json",
    "type": "mcode",
    "machineType": "mill",
    "title": "M Code Milling Reference",
    "description": "M Code Reference for Milling Machine Tools",
    "keywords": ["mazak", "mill", "milling"],
    "codes": {
        "M00": {
            "category": "mcode",
            "shortDesc": "Program Stop",
            "desc": "Program Stop"
        }
    }
}

=== appliedengdesign/cnccodes-json-schema/test/sample/m-sample.json
{
    "$schema": "../../src/schema/cnccodes.schema.json",
    "type": "mcode",
    "machineType": "mill",
    "title": "M Code Milling Reference",
    "description": "M Code Reference for Milling Machine Tools",
    "codes": {
        "M00": {
            "category": "mcode",
            "shortDesc": "Program Stop",
            "desc": "Program Stop"
        }
    }
}
